apiVersion: v2
name: mirador-core
description: Helm chart for MIRADOR-CORE (Advanced Observability Platform - Backend REST API Service)
type: application
version: 0.2.0
appVersion: "v9.0.0"

dependencies:
  - name: valkey
    repository: https://charts.bitnami.com/bitnami
    version: ^2.0.0
    condition: valkey.enabled
  - name: weaviate
    repository: file://charts/weaviate
    version: 0.1.0
    condition: weaviate.enabled
